import AppKit
import Sparkle

/// Owns the Sparkle updater controller and exposes a `checkForUpdates()`
/// entry point for the menu-bar item. We use the standard Sparkle UI
/// (Sparkle handles all the dialogs / progress bars), so all we have to
/// do is keep the controller alive for the lifetime of the app.
///
/// Required Info.plist keys (must be set before publishing a release):
///   • `SUFeedURL`     — HTTPS URL of the appcast.xml hosted somewhere
///                       reachable (GitHub Pages or similar).
///   • `SUPublicEDKey` — Base64 EdDSA public key generated by
///                       `Frameworks/Sparkle/bin/generate_keys`. The
///                       matching private key signs each release.
final class Updater {

    static let shared = Updater()

    private let controller: SPUStandardUpdaterController

    private init() {
        controller = SPUStandardUpdaterController(
            startingUpdater: true,
            updaterDelegate: nil,
            userDriverDelegate: nil
        )
    }

    func checkForUpdates() {
        controller.checkForUpdates(nil)
    }
}
