#!/usr/bin/env bash
# Build Skald.app without Xcode — straight swiftc + manual bundle.
set -euo pipefail

cd "$(dirname "$0")"

BUNDLE="Skald.app"
BIN_NAME="Skald"
MIN_MACOS="15.0"   # Apple Translation framework requires macOS 15+

# Code-signing identity. Override via env var, e.g.:
#   SKALD_SIGN_IDENTITY="Developer ID Application: …" ./build.sh
# Default to a stable self-signed dev cert in the login keychain (so that
# TCC grants survive rebuilds during development). Fall back to ad-hoc if
# the identity isn't available.
SIGN_IDENTITY="${SKALD_SIGN_IDENTITY:-Translator Dev (self-signed)}"
if ! security find-identity -v -p codesigning | grep -q "$SIGN_IDENTITY"; then
  echo "!! '$SIGN_IDENTITY' not found in keychain — falling back to ad-hoc"
  SIGN_IDENTITY="-"
fi

# Build a universal binary by default (arm64 + x86_64) so the same .zip
# runs on both Apple Silicon and Intel Macs. Override with
# `SKALD_BUILD_ARCH=native` to compile only for the host arch (faster
# during dev).
HOST_ARCH="$(uname -m)"
if [ "${SKALD_BUILD_ARCH:-universal}" = "native" ]; then
  case "$HOST_ARCH" in
    arm64)  ARCHES=("arm64") ;;
    x86_64) ARCHES=("x86_64") ;;
    *) echo "unsupported arch: $HOST_ARCH" >&2; exit 1 ;;
  esac
else
  ARCHES=("arm64" "x86_64")
fi

echo "==> Cleaning old bundle"
rm -rf "$BUNDLE"

echo "==> Creating bundle skeleton"
mkdir -p "$BUNDLE/Contents/MacOS" "$BUNDLE/Contents/Resources"
cp Info.plist "$BUNDLE/Contents/Info.plist"

# App icon — generated by make-icon.sh from a master PNG. Optional in dev
# (the build still works without an icon), required for release.
if [ -f Resources/Skald.icns ]; then
  cp Resources/Skald.icns "$BUNDLE/Contents/Resources/Skald.icns"
else
  echo "(!) Resources/Skald.icns missing — building without an app icon."
  echo "    Run ./make-icon.sh icon-source.png to generate one."
fi

echo "==> Embedding Sparkle.framework"
mkdir -p "$BUNDLE/Contents/Frameworks"
cp -R Frameworks/Sparkle.framework "$BUNDLE/Contents/Frameworks/Sparkle.framework"

SLICE_DIR="$(mktemp -d)"
trap 'rm -rf "$SLICE_DIR"' EXIT

SLICES=()
for ARCH in "${ARCHES[@]}"; do
  TARGET="${ARCH}-apple-macosx${MIN_MACOS}"
  OUT="$SLICE_DIR/$BIN_NAME.$ARCH"
  echo "==> Compiling Swift sources ($TARGET)"
  swiftc \
    -O \
    -target "$TARGET" \
    -framework AppKit \
    -framework Carbon \
    -F Frameworks \
    -framework Sparkle \
    -Xlinker -rpath -Xlinker "@executable_path/../Frameworks" \
    -o "$OUT" \
    Sources/*.swift
  SLICES+=("$OUT")
done

if [ "${#SLICES[@]}" -gt 1 ]; then
  echo "==> Combining ${#SLICES[@]} arch slices into a universal binary"
  lipo -create "${SLICES[@]}" -output "$BUNDLE/Contents/MacOS/$BIN_NAME"
else
  cp "${SLICES[0]}" "$BUNDLE/Contents/MacOS/$BIN_NAME"
fi

echo "==> Signing"
# Sign embedded framework + nested helpers first, then the outer app.
# Sparkle ships XPC services and an Updater helper that all need to be
# signed individually for Gatekeeper to accept the bundle.
codesign -s "$SIGN_IDENTITY" --force --options=runtime --timestamp=none \
  "$BUNDLE/Contents/Frameworks/Sparkle.framework/Versions/Current/XPCServices/Downloader.xpc" 2>/dev/null || true
codesign -s "$SIGN_IDENTITY" --force --options=runtime --timestamp=none \
  "$BUNDLE/Contents/Frameworks/Sparkle.framework/Versions/Current/XPCServices/Installer.xpc" 2>/dev/null || true
codesign -s "$SIGN_IDENTITY" --force --options=runtime --timestamp=none \
  "$BUNDLE/Contents/Frameworks/Sparkle.framework/Versions/Current/Updater.app" 2>/dev/null || true
codesign -s "$SIGN_IDENTITY" --force --options=runtime --timestamp=none \
  "$BUNDLE/Contents/Frameworks/Sparkle.framework/Versions/Current/Autoupdate" 2>/dev/null || true
codesign -s "$SIGN_IDENTITY" --force --options=runtime --timestamp=none \
  "$BUNDLE/Contents/Frameworks/Sparkle.framework"
codesign -s "$SIGN_IDENTITY" --force --deep --options=runtime \
  --entitlements Skald.entitlements "$BUNDLE" >/dev/null

echo "==> Done: $(pwd)/$BUNDLE"
